function b64_sha1(d){return binb2b64(core_sha1(str2binb(d),8*d.length))}function str_sha1(d){return binb2str(core_sha1(str2binb(d),8*d.length))}function b64_hmac_sha1(d,g){return binb2b64(core_hmac_sha1(d,g))}function str_hmac_sha1(d,g){return binb2str(core_hmac_sha1(d,g))}
function core_sha1(d,g){d[g>>5]|=128<<24-g%32;d[(g+64>>9<<4)+15]=g;var e,h,c,b,a,f,k,v,t=Array(80),r=1732584193,s=-271733879,l=-1732584194,m=271733878,n=-1009589776;for(e=0;e<d.length;e+=16){b=r;a=s;f=l;k=m;v=n;for(h=0;80>h;h++)t[h]=16>h?d[e+h]:rol(t[h-3]^t[h-8]^t[h-14]^t[h-16],1),c=safe_add(safe_add(rol(r,5),sha1_ft(h,s,l,m)),safe_add(safe_add(n,t[h]),sha1_kt(h))),n=m,m=l,l=rol(s,30),s=r,r=c;r=safe_add(r,b);s=safe_add(s,a);l=safe_add(l,f);m=safe_add(m,k);n=safe_add(n,v)}return[r,s,l,m,n]}
function sha1_ft(d,g,e,h){return 20>d?g&e|~g&h:40>d?g^e^h:60>d?g&e|g&h|e&h:g^e^h}function sha1_kt(d){return 20>d?1518500249:40>d?1859775393:60>d?-1894007588:-899497514}function core_hmac_sha1(d,g){var e=str2binb(d);16<e.length&&(e=core_sha1(e,8*d.length));for(var h=Array(16),c=Array(16),b=0;16>b;b++)h[b]=909522486^e[b],c[b]=1549556828^e[b];e=core_sha1(h.concat(str2binb(g)),512+8*g.length);return core_sha1(c.concat(e),672)}
function safe_add(d,g){var e=(65535&d)+(65535&g);return(d>>16)+(g>>16)+(e>>16)<<16|65535&e}function rol(d,g){return d<<g|d>>>32-g}function str2binb(d){for(var g=[],e=0;e<8*d.length;e+=8)g[e>>5]|=(d.charCodeAt(e/8)&255)<<24-e%32;return g}function binb2str(d){for(var g="",e=0;e<32*d.length;e+=8)g+=String.fromCharCode(d[e>>5]>>>24-e%32&255);return g}
function binb2b64(d){for(var g,e,h="",c=0;c<4*d.length;c+=3)for(g=(d[c>>2]>>8*(3-c%4)&255)<<16|(d[c+1>>2]>>8*(3-(c+1)%4)&255)<<8|d[c+2>>2]>>8*(3-(c+2)%4)&255,e=0;4>e;e++)h+=8*c+6*e>32*d.length?"=":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(g>>6*(3-e)&63);return h}
var Base64=function(){return{encode:function(d){var g,e,h,c,b,a,f="",k=0;do g=d.charCodeAt(k++),e=d.charCodeAt(k++),h=d.charCodeAt(k++),c=g>>2,g=(3&g)<<4|e>>4,b=(15&e)<<2|h>>6,a=63&h,isNaN(e)?b=a=64:isNaN(h)&&(a=64),f=f+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a);
while(k<d.length);return f},decode:function(d){var g,e,h,c,b,a="",f=0;d=d.replace(/[^A-Za-z0-9\+\/\=]/g,"");do g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(f++)),e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(f++)),c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(f++)),b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(d.charAt(f++)),g=g<<2|e>>4,e=(15&
e)<<4|c>>2,h=(3&c)<<6|b,a+=String.fromCharCode(g),64!=c&&(a+=String.fromCharCode(e)),64!=b&&(a+=String.fromCharCode(h));while(f<d.length);return a}}}(),MD5=function(){var d=function(a,b){var c=(65535&a)+(65535&b);return(a>>16)+(b>>16)+(c>>16)<<16|65535&c},g=function(a){for(var b=[],c=0;c<8*a.length;c+=8)b[c>>5]|=(255&a.charCodeAt(c/8))<<c%32;return b},e=function(a,b,c,e,g,h){a=d(d(b,a),d(e,h));return d(a<<g|a>>>32-g,c)},h=function(a,b,c,d,g,h,l){return e(b&c|~b&d,a,b,g,h,l)},c=function(a,b,c,d,g,
h,l){return e(b&d|c&~d,a,b,g,h,l)},b=function(a,b,c,d,g,h,l){return e(c^(b|~d),a,b,g,h,l)},a=function(a,k){a[k>>5]|=128<<k%32;a[(k+64>>>9<<4)+14]=k;for(var g,t,r,s,l=1732584193,m=-271733879,n=-1732584194,p=271733878,q=0;q<a.length;q+=16)g=l,t=m,r=n,s=p,l=h(l,m,n,p,a[q+0],7,-680876936),p=h(p,l,m,n,a[q+1],12,-389564586),n=h(n,p,l,m,a[q+2],17,606105819),m=h(m,n,p,l,a[q+3],22,-1044525330),l=h(l,m,n,p,a[q+4],7,-176418897),p=h(p,l,m,n,a[q+5],12,1200080426),n=h(n,p,l,m,a[q+6],17,-1473231341),m=h(m,n,p,l,
a[q+7],22,-45705983),l=h(l,m,n,p,a[q+8],7,1770035416),p=h(p,l,m,n,a[q+9],12,-1958414417),n=h(n,p,l,m,a[q+10],17,-42063),m=h(m,n,p,l,a[q+11],22,-1990404162),l=h(l,m,n,p,a[q+12],7,1804603682),p=h(p,l,m,n,a[q+13],12,-40341101),n=h(n,p,l,m,a[q+14],17,-1502002290),m=h(m,n,p,l,a[q+15],22,1236535329),l=c(l,m,n,p,a[q+1],5,-165796510),p=c(p,l,m,n,a[q+6],9,-1069501632),n=c(n,p,l,m,a[q+11],14,643717713),m=c(m,n,p,l,a[q+0],20,-373897302),l=c(l,m,n,p,a[q+5],5,-701558691),p=c(p,l,m,n,a[q+10],9,38016083),n=c(n,
p,l,m,a[q+15],14,-660478335),m=c(m,n,p,l,a[q+4],20,-405537848),l=c(l,m,n,p,a[q+9],5,568446438),p=c(p,l,m,n,a[q+14],9,-1019803690),n=c(n,p,l,m,a[q+3],14,-187363961),m=c(m,n,p,l,a[q+8],20,1163531501),l=c(l,m,n,p,a[q+13],5,-1444681467),p=c(p,l,m,n,a[q+2],9,-51403784),n=c(n,p,l,m,a[q+7],14,1735328473),m=c(m,n,p,l,a[q+12],20,-1926607734),l=e(m^n^p,l,m,a[q+5],4,-378558),p=e(l^m^n,p,l,a[q+8],11,-2022574463),n=e(p^l^m,n,p,a[q+11],16,1839030562),m=e(n^p^l,m,n,a[q+14],23,-35309556),l=e(m^n^p,l,m,a[q+1],4,-1530992060),
p=e(l^m^n,p,l,a[q+4],11,1272893353),n=e(p^l^m,n,p,a[q+7],16,-155497632),m=e(n^p^l,m,n,a[q+10],23,-1094730640),l=e(m^n^p,l,m,a[q+13],4,681279174),p=e(l^m^n,p,l,a[q+0],11,-358537222),n=e(p^l^m,n,p,a[q+3],16,-722521979),m=e(n^p^l,m,n,a[q+6],23,76029189),l=e(m^n^p,l,m,a[q+9],4,-640364487),p=e(l^m^n,p,l,a[q+12],11,-421815835),n=e(p^l^m,n,p,a[q+15],16,530742520),m=e(n^p^l,m,n,a[q+2],23,-995338651),l=b(l,m,n,p,a[q+0],6,-198630844),p=b(p,l,m,n,a[q+7],10,1126891415),n=b(n,p,l,m,a[q+14],15,-1416354905),m=b(m,
n,p,l,a[q+5],21,-57434055),l=b(l,m,n,p,a[q+12],6,1700485571),p=b(p,l,m,n,a[q+3],10,-1894986606),n=b(n,p,l,m,a[q+10],15,-1051523),m=b(m,n,p,l,a[q+1],21,-2054922799),l=b(l,m,n,p,a[q+8],6,1873313359),p=b(p,l,m,n,a[q+15],10,-30611744),n=b(n,p,l,m,a[q+6],15,-1560198380),m=b(m,n,p,l,a[q+13],21,1309151649),l=b(l,m,n,p,a[q+4],6,-145523070),p=b(p,l,m,n,a[q+11],10,-1120210379),n=b(n,p,l,m,a[q+2],15,718787259),m=b(m,n,p,l,a[q+9],21,-343485551),l=d(l,g),m=d(m,t),n=d(n,r),p=d(p,s);return[l,m,n,p]};return{hexdigest:function(b){b=
a(g(b),8*b.length);for(var k="",c=0;c<4*b.length;c++)k+="0123456789abcdef".charAt(b[c>>2]>>c%4*8+4&15)+"0123456789abcdef".charAt(b[c>>2]>>c%4*8&15);return k},hash:function(b){b=a(g(b),8*b.length);for(var k="",c=0;c<32*b.length;c+=8)k+=String.fromCharCode(b[c>>5]>>>c%32&255);return k}}}();
Function.prototype.bind||(Function.prototype.bind=function(d){var g=this,e=Array.prototype.slice,h=Array.prototype.concat,c=e.call(arguments,1);return function(){return g.apply(d?d:this,h.call(c,e.call(arguments,0)))}});Array.prototype.indexOf||(Array.prototype.indexOf=function(d,g){var e=this.length,h=Number(g)||0,h=0>h?Math.ceil(h):Math.floor(h);for(0>h&&(h+=e);e>h;h++)if(h in this&&this[h]===d)return h;return-1});
(function(d){function g(a,f){return new b.Builder(a,f)}function e(a){return new b.Builder("message",a)}function h(a){return new b.Builder("iq",a)}function c(a){return new b.Builder("presence",a)}var b;b={VERSION:"1.1.3",NS:{HTTPBIND:"http://jabber.org/protocol/httpbind",BOSH:"urn:xmpp:xbosh",CLIENT:"jabber:client",AUTH:"jabber:iq:auth",ROSTER:"jabber:iq:roster",PROFILE:"jabber:iq:profile",DISCO_INFO:"http://jabber.org/protocol/disco#info",DISCO_ITEMS:"http://jabber.org/protocol/disco#items",MUC:"http://jabber.org/protocol/muc",
SASL:"urn:ietf:params:xml:ns:xmpp-sasl",STREAM:"http://etherx.jabber.org/streams",BIND:"urn:ietf:params:xml:ns:xmpp-bind",SESSION:"urn:ietf:params:xml:ns:xmpp-session",VERSION:"jabber:iq:version",STANZAS:"urn:ietf:params:xml:ns:xmpp-stanzas",XHTML_IM:"http://jabber.org/protocol/xhtml-im",XHTML:"http://www.w3.org/1999/xhtml"},XHTML:{tags:"a blockquote br cite em img li ol p span strong ul body".split(" "),attributes:{a:["href"],blockquote:["style"],br:[],cite:["style"],em:[],img:["src","alt","style",
"height","width"],li:["style"],ol:["style"],p:["style"],span:["style"],strong:[],ul:["style"],body:[]},css:"background-color color font-family font-size font-style font-weight margin-left margin-right text-align text-decoration".split(" "),validTag:function(a){for(var f=0;f<b.XHTML.tags.length;f++)if(a==b.XHTML.tags[f])return!0;return!1},validAttribute:function(a,f){if("undefined"!=typeof b.XHTML.attributes[a]&&0<b.XHTML.attributes[a].length)for(var k=0;k<b.XHTML.attributes[a].length;k++)if(f==b.XHTML.attributes[a][k])return!0;
return!1},validCSS:function(a){for(var f=0;f<b.XHTML.css.length;f++)if(a==b.XHTML.css[f])return!0;return!1}},Status:{ERROR:0,CONNECTING:1,CONNFAIL:2,AUTHENTICATING:3,AUTHFAIL:4,CONNECTED:5,DISCONNECTED:6,DISCONNECTING:7,ATTACHED:8},LogLevel:{DEBUG:0,INFO:1,WARN:2,ERROR:3,FATAL:4},ElementType:{NORMAL:1,TEXT:3,CDATA:4,FRAGMENT:11},TIMEOUT:1.1,SECONDARY_TIMEOUT:.1,addNamespace:function(a,f){b.NS[a]=f},forEachChild:function(a,f,k){var c,d;for(c=0;c<a.childNodes.length;c++)d=a.childNodes[c],d.nodeType!=
b.ElementType.NORMAL||f&&!this.isTagEqual(d,f)||k(d)},isTagEqual:function(a,b){return a.tagName.toLowerCase()==b.toLowerCase()},_xmlGenerator:null,_makeGenerator:function(){var a;return void 0===document.implementation.createDocument||document.implementation.createDocument&&document.documentMode&&10>document.documentMode?(a=this._getIEXmlDom(),a.appendChild(a.createElement("strophe"))):a=document.implementation.createDocument("jabber:client","strophe",null),a},xmlGenerator:function(){return b._xmlGenerator||
(b._xmlGenerator=b._makeGenerator()),b._xmlGenerator},_getIEXmlDom:function(){for(var a=null,b="Msxml2.DOMDocument.6.0 Msxml2.DOMDocument.5.0 Msxml2.DOMDocument.4.0 MSXML2.DOMDocument.3.0 MSXML2.DOMDocument MSXML.DOMDocument Microsoft.XMLDOM".split(" "),k=0;k<b.length&&null===a;k++)try{a=new ActiveXObject(b[k])}catch(c){a=null}return a},xmlElement:function(a){if(!a)return null;var f,k,c,d=b.xmlGenerator().createElement(a);for(f=1;f<arguments.length;f++)if(arguments[f])if("string"==typeof arguments[f]||
"number"==typeof arguments[f])d.appendChild(b.xmlTextNode(arguments[f]));else if("object"==typeof arguments[f]&&"function"==typeof arguments[f].sort)for(k=0;k<arguments[f].length;k++)"object"==typeof arguments[f][k]&&"function"==typeof arguments[f][k].sort&&d.setAttribute(arguments[f][k][0],arguments[f][k][1]);else if("object"==typeof arguments[f])for(c in arguments[f])arguments[f].hasOwnProperty(c)&&d.setAttribute(c,arguments[f][c]);return d},xmlescape:function(a){return a=a.replace(/\&/g,"&amp;"),
a=a.replace(/</g,"&lt;"),a=a.replace(/>/g,"&gt;"),a=a.replace(/'/g,"&apos;"),a.replace(/"/g,"&quot;")},xmlTextNode:function(a){return b.xmlGenerator().createTextNode(a)},xmlHtmlNode:function(a){var b;window.DOMParser?b=(new DOMParser).parseFromString(a,"text/xml"):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a));return b},getText:function(a){if(!a)return null;var f="";0===a.childNodes.length&&a.nodeType==b.ElementType.TEXT&&(f+=a.nodeValue);for(var k=0;k<a.childNodes.length;k++)a.childNodes[k].nodeType==
b.ElementType.TEXT&&(f+=a.childNodes[k].nodeValue);return b.xmlescape(f)},copyElement:function(a){var f,k;if(a.nodeType==b.ElementType.NORMAL){k=b.xmlElement(a.tagName);for(f=0;f<a.attributes.length;f++)k.setAttribute(a.attributes[f].nodeName.toLowerCase(),a.attributes[f].value);for(f=0;f<a.childNodes.length;f++)k.appendChild(b.copyElement(a.childNodes[f]))}else a.nodeType==b.ElementType.TEXT&&(k=b.xmlGenerator().createTextNode(a.nodeValue));return k},createHtml:function(a){var f,k,c,d,e,g,h,m,n,
p,q;if(a.nodeType==b.ElementType.NORMAL)if(d=a.nodeName.toLowerCase(),b.XHTML.validTag(d))try{k=b.xmlElement(d);for(f=0;f<b.XHTML.attributes[d].length;f++)if(e=b.XHTML.attributes[d][f],g=a.getAttribute(e),"undefined"!=typeof g&&null!==g&&""!==g&&!1!==g&&0!==g)if("style"==e&&"object"==typeof g&&"undefined"!=typeof g.cssText&&(g=g.cssText),"style"==e){h=[];m=g.split(";");for(c=0;c<m.length;c++)n=m[c].split(":"),p=n[0].replace(/^\s*/,"").replace(/\s*$/,"").toLowerCase(),b.XHTML.validCSS(p)&&(q=n[1].replace(/^\s*/,
"").replace(/\s*$/,""),h.push(p+": "+q));0<h.length&&(g=h.join("; "),k.setAttribute(e,g))}else k.setAttribute(e,g);for(f=0;f<a.childNodes.length;f++)k.appendChild(b.createHtml(a.childNodes[f]))}catch(u){k=b.xmlTextNode("")}else for(k=b.xmlGenerator().createDocumentFragment(),f=0;f<a.childNodes.length;f++)k.appendChild(b.createHtml(a.childNodes[f]));else if(a.nodeType==b.ElementType.FRAGMENT)for(k=b.xmlGenerator().createDocumentFragment(),f=0;f<a.childNodes.length;f++)k.appendChild(b.createHtml(a.childNodes[f]));
else a.nodeType==b.ElementType.TEXT&&(k=b.xmlTextNode(a.nodeValue));return k},escapeNode:function(a){return a.replace(/^\s+|\s+$/g,"").replace(/\\/g,"\\5c").replace(/ /g,"\\20").replace(/\"/g,"\\22").replace(/\&/g,"\\26").replace(/\'/g,"\\27").replace(/\//g,"\\2f").replace(/:/g,"\\3a").replace(/</g,"\\3c").replace(/>/g,"\\3e").replace(/@/g,"\\40")},unescapeNode:function(a){return a.replace(/\\20/g," ").replace(/\\22/g,'"').replace(/\\26/g,"&").replace(/\\27/g,"'").replace(/\\2f/g,"/").replace(/\\3a/g,
":").replace(/\\3c/g,"<").replace(/\\3e/g,">").replace(/\\40/g,"@").replace(/\\5c/g,"\\")},getNodeFromJid:function(a){return 0>a.indexOf("@")?null:a.split("@")[0]},getDomainFromJid:function(a){a=b.getBareJidFromJid(a);if(0>a.indexOf("@"))return a;a=a.split("@");return a.splice(0,1),a.join("@")},getResourceFromJid:function(a){a=a.split("/");return 2>a.length?null:(a.splice(0,1),a.join("/"))},getBareJidFromJid:function(a){return a?a.split("/")[0]:null},log:function(){},debug:function(a){this.log(this.LogLevel.DEBUG,
a)},info:function(a){this.log(this.LogLevel.INFO,a)},warn:function(a){this.log(this.LogLevel.WARN,a)},error:function(a){this.log(this.LogLevel.ERROR,a)},fatal:function(a){this.log(this.LogLevel.FATAL,a)},serialize:function(a){var f;if(!a)return null;"function"==typeof a.tree&&(a=a.tree());var k,c,d=a.nodeName;a.getAttribute("_realname")&&(d=a.getAttribute("_realname"));f="<"+d;for(k=0;k<a.attributes.length;k++)"_realname"!=a.attributes[k].nodeName&&(f+=" "+a.attributes[k].nodeName.toLowerCase()+"='"+
a.attributes[k].value.replace(/&/g,"&amp;").replace(/\'/g,"&apos;").replace(/>/g,"&gt;").replace(/</g,"&lt;")+"'");if(0<a.childNodes.length){f+=">";for(k=0;k<a.childNodes.length;k++)switch(c=a.childNodes[k],c.nodeType){case b.ElementType.NORMAL:f+=b.serialize(c);break;case b.ElementType.TEXT:f+=b.xmlescape(c.nodeValue);break;case b.ElementType.CDATA:f+="<![CDATA["+c.nodeValue+"]]\x3e"}f+="</"+d+">"}else f+="/>";return f},_requestId:0,_connectionPlugins:{},addConnectionPlugin:function(a,f){b._connectionPlugins[a]=
f},Builder:function(a,f){("presence"==a||"message"==a||"iq"==a)&&(f&&!f.xmlns?f.xmlns=b.NS.CLIENT:f||(f={xmlns:b.NS.CLIENT}));this.node=this.nodeTree=b.xmlElement(a,f)}};b.Builder.prototype={tree:function(){return this.nodeTree},toString:function(){return b.serialize(this.nodeTree)},up:function(){return this.node=this.node.parentNode,this},attrs:function(a){for(var b in a)a.hasOwnProperty(b)&&this.node.setAttribute(b,a[b]);return this},c:function(a,f,k){a=b.xmlElement(a,f,k);return this.node.appendChild(a),
k||(this.node=a),this},cnode:function(a){var f,k=b.xmlGenerator();try{f=void 0!==k.importNode}catch(c){f=!1}a=f?k.importNode(a,!0):b.copyElement(a);return this.node.appendChild(a),this.node=a,this},t:function(a){a=b.xmlTextNode(a);return this.node.appendChild(a),this},h:function(a){var f=document.createElement("body");f.innerHTML=a;for(a=b.createHtml(f);0<a.childNodes.length;)this.node.appendChild(a.childNodes[0]);return this}};b.Handler=function(a,f,k,c,d,e,g){this.handler=a;this.ns=f;this.name=
k;this.type=c;this.id=d;this.options=g||{matchBare:!1};this.options.matchBare||(this.options.matchBare=!1);this.from=this.options.matchBare?e?b.getBareJidFromJid(e):null:e;this.user=!0};b.Handler.prototype={isMatch:function(a){var f,k=null;if(k=this.options.matchBare?b.getBareJidFromJid(a.getAttribute("from")):a.getAttribute("from"),f=!1,this.ns){var c=this;b.forEachChild(a,null,function(a){a.getAttribute("xmlns")==c.ns&&(f=!0)});f=f||a.getAttribute("xmlns")==this.ns}else f=!0;return!f||this.name&&
!b.isTagEqual(a,this.name)||this.type&&a.getAttribute("type")!=this.type||this.id&&a.getAttribute("id")!=this.id||this.from&&k!=this.from?!1:!0},run:function(a){var f=null;try{f=this.handler(a)}catch(k){throw k.sourceURL?b.fatal("error: "+this.handler+" "+k.sourceURL+":"+k.line+" - "+k.name+": "+k.message):k.fileName?("undefined"!=typeof console&&(console.trace(),console.error(this.handler," - error - ",k,k.message)),b.fatal("error: "+this.handler+" "+k.fileName+":"+k.lineNumber+" - "+k.name+": "+
k.message)):b.fatal("error: "+k.message+"\n"+k.stack),k;}return f},toString:function(){return"{Handler: "+this.handler+"("+this.name+","+this.id+","+this.ns+")}"}};b.TimedHandler=function(a,b){this.period=a;this.handler=b;this.lastCalled=(new Date).getTime();this.user=!0};b.TimedHandler.prototype={run:function(){return this.lastCalled=(new Date).getTime(),this.handler()},reset:function(){this.lastCalled=(new Date).getTime()},toString:function(){return"{TimedHandler: "+this.handler+"("+this.period+
")}"}};b.Connection=function(a,f){this.service=a;this.options=f||{};var k=this.options.protocol||"";this._proto=0===a.indexOf("ws:")||0===a.indexOf("wss:")||0===k.indexOf("ws")?new b.Websocket(this):new b.Bosh(this);this.jid="";this.features=this.domain=null;this._sasl_data={};this.do_bind=this.do_session=!1;this.timedHandlers=[];this.handlers=[];this.removeTimeds=[];this.removeHandlers=[];this.addTimeds=[];this.addHandlers=[];this._authentication={};this._disconnectTimeout=this._idleTimeout=null;
this.do_authentication=!0;this.connected=this.disconnecting=this.authenticated=!1;this.errors=0;this.paused=!1;this._data=[];this._uniqueId=0;this._sasl_challenge_handler=this._sasl_failure_handler=this._sasl_success_handler=null;this.maxRetries=5;this._idleTimeout=setTimeout(this._onIdle.bind(this),100);for(var c in b._connectionPlugins)b._connectionPlugins.hasOwnProperty(c)&&(k=function(){},k.prototype=b._connectionPlugins[c],this[c]=new k,this[c].init(this))};b.Connection.prototype={reset:function(){this._proto._reset();
this.do_bind=this.do_session=!1;this.timedHandlers=[];this.handlers=[];this.removeTimeds=[];this.removeHandlers=[];this.addTimeds=[];this.addHandlers=[];this._authentication={};this.connected=this.disconnecting=this.authenticated=!1;this.errors=0;this._requests=[];this._uniqueId=0},pause:function(){this.paused=!0},resume:function(){this.paused=!1},getUniqueId:function(a){return"string"==typeof a||"number"==typeof a?++this._uniqueId+":"+a:++this._uniqueId+""},connect:function(a,f,c,d,e,g){this.jid=
a;this.authzid=b.getBareJidFromJid(this.jid);this.authcid=b.getNodeFromJid(this.jid);this.pass=f;this.servtype="xmpp";this.connect_callback=c;this.authenticated=this.connected=this.disconnecting=!1;this.errors=0;this.domain=b.getDomainFromJid(this.jid);this._changeConnectStatus(b.Status.CONNECTING,null);this._proto._connect(d,e,g)},attach:function(a,b,c,d,e,g,h){this._proto._attach(a,b,c,d,e,g,h)},xmlInput:function(){},xmlOutput:function(){},rawInput:function(){},rawOutput:function(){},send:function(a){if(null!==
a){if("function"==typeof a.sort)for(var b=0;b<a.length;b++)this._queueData(a[b]);else"function"==typeof a.tree?this._queueData(a.tree()):this._queueData(a);this._proto._send()}},flush:function(){clearTimeout(this._idleTimeout);this._onIdle()},sendIQ:function(a,b,c,d){var e=null,g=this;"function"==typeof a.tree&&(a=a.tree());var h=a.getAttribute("id");h||(h=this.getUniqueId("sendIQ"),a.setAttribute("id",h));var l=this.addHandler(function(a){e&&g.deleteTimedHandler(e);var d=a.getAttribute("type");if("result"==
d)b&&b(a);else{if("error"!=d)throw{name:"StropheError",message:"Got bad IQ type of "+d};c&&c(a)}},null,"iq",null,h);return d&&(e=this.addTimedHandler(d,function(){return g.deleteHandler(l),c&&c(null),!1})),this.send(a),h},_queueData:function(a){if(null===a||!a.tagName||!a.childNodes)throw{name:"StropheError",message:"Cannot queue non-DOMElement."};this._data.push(a)},_sendRestart:function(){this._data.push("restart");this._proto._sendRestart();this._idleTimeout=setTimeout(this._onIdle.bind(this),
100)},addTimedHandler:function(a,f){var c=new b.TimedHandler(a,f);return this.addTimeds.push(c),c},deleteTimedHandler:function(a){this.removeTimeds.push(a)},addHandler:function(a,f,c,d,e,g,h){a=new b.Handler(a,f,c,d,e,g,h);return this.addHandlers.push(a),a},deleteHandler:function(a){this.removeHandlers.push(a)},disconnect:function(a){if(this._changeConnectStatus(b.Status.DISCONNECTING,a),b.info("Disconnect was called because: "+a),this.connected)a=!1,this.disconnecting=!0,this.authenticated&&(a=c({xmlns:b.NS.CLIENT,
type:"unavailable"})),this._disconnectTimeout=this._addSysTimedHandler(3E3,this._onDisconnectTimeout.bind(this)),this._proto._disconnect(a)},_changeConnectStatus:function(a,f){for(var c in b._connectionPlugins)if(b._connectionPlugins.hasOwnProperty(c)){var d=this[c];if(d.statusChanged)try{d.statusChanged(a,f)}catch(e){b.error(""+c+" plugin caused an exception changing status: "+e)}}if(this.connect_callback)try{this.connect_callback(a,f)}catch(g){b.error("User connection callback caused an exception: "+
g)}},_doDisconnect:function(){null!==this._disconnectTimeout&&(this.deleteTimedHandler(this._disconnectTimeout),this._disconnectTimeout=null);b.info("_doDisconnect was called");this._proto._doDisconnect();this.disconnecting=this.authenticated=!1;this.handlers=[];this.timedHandlers=[];this.removeTimeds=[];this.removeHandlers=[];this.addTimeds=[];this.addHandlers=[];this._changeConnectStatus(b.Status.DISCONNECTED,null);this.connected=!1},_dataRecv:function(a,f){b.info("_dataRecv called");var c=this._proto._reqToData(a);
if(null!==c){this.xmlInput!==b.Connection.prototype.xmlInput&&(c.nodeName===this._proto.strip&&c.childNodes.length?this.xmlInput(c.childNodes[0]):this.xmlInput(c));this.rawInput!==b.Connection.prototype.rawInput&&(f?this.rawInput(f):this.rawInput(b.serialize(c)));for(var d;0<this.removeHandlers.length;)d=this.removeHandlers.pop(),d=this.handlers.indexOf(d),0<=d&&this.handlers.splice(d,1);for(;0<this.addHandlers.length;)this.handlers.push(this.addHandlers.pop());if(this.disconnecting&&this._proto._emptyQueue())return this._doDisconnect(),
void 0;var e,g;d=c.getAttribute("type");if(null!==d&&"terminate"==d)return this.disconnecting?void 0:(e=c.getAttribute("condition"),g=c.getElementsByTagName("conflict"),null!==e?("remote-stream-error"==e&&0<g.length&&(e="conflict"),this._changeConnectStatus(b.Status.CONNFAIL,e)):this._changeConnectStatus(b.Status.CONNFAIL,"unknown"),this.disconnect("unknown stream-error"),void 0);var h=this;b.forEachChild(c,null,function(a){var f,c;c=h.handlers;h.handlers=[];for(f=0;f<c.length;f++){var d=c[f];try{!d.isMatch(a)||
!h.authenticated&&d.user?h.handlers.push(d):d.run(a)&&h.handlers.push(d)}catch(k){b.warn("Removing Strophe handlers due to uncaught exception: "+k.message)}}})}},mechanisms:{},_connect_cb:function(a,f,c){b.info("_connect_cb was called");this.connected=!0;if(a=this._proto._reqToData(a))if(this.xmlInput!==b.Connection.prototype.xmlInput&&(a.nodeName===this._proto.strip&&a.childNodes.length?this.xmlInput(a.childNodes[0]):this.xmlInput(a)),this.rawInput!==b.Connection.prototype.rawInput&&(c?this.rawInput(c):
this.rawInput(b.serialize(a))),this._proto._connect_cb(a)!==b.Status.CONNFAIL){this._authentication.sasl_scram_sha1=!1;this._authentication.sasl_plain=!1;this._authentication.sasl_digest_md5=!1;this._authentication.sasl_anonymous=!1;this._authentication.legacy_auth=!1;var d=0<a.getElementsByTagName("stream:features").length;d||(d=0<a.getElementsByTagName("features").length);var e;c=a.getElementsByTagName("mechanism");var g=[];if(!d)return this._proto._no_auth_received(f),void 0;if(0<c.length)for(d=
0;d<c.length;d++)e=b.getText(c[d]),this.mechanisms[e]&&g.push(this.mechanisms[e]);return this._authentication.legacy_auth=0<a.getElementsByTagName("auth").length,this._authentication.legacy_auth||0<g.length?(!1!==this.do_authentication&&this.authenticate(g),void 0):(this._proto._no_auth_received(f),void 0)}},authenticate:function(a){var f;for(f=0;f<a.length-1;++f){for(var c=f,d=f+1;d<a.length;++d)a[d].prototype.priority>a[c].prototype.priority&&(c=d);c!=f&&(d=a[f],a[f]=a[c],a[c]=d)}c=!1;for(f=0;f<
a.length;++f)if(a[f].test(this)){this._sasl_success_handler=this._addSysHandler(this._sasl_success_cb.bind(this),null,"success",null,null);this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,"failure",null,null);this._sasl_challenge_handler=this._addSysHandler(this._sasl_challenge_cb.bind(this),null,"challenge",null,null);this._sasl_mechanism=new a[f];this._sasl_mechanism.onStart(this);a=g("auth",{xmlns:b.NS.SASL,mechanism:this._sasl_mechanism.name});this._sasl_mechanism.isClientFirst&&
(f=this._sasl_mechanism.onChallenge(this,null),a.t(Base64.encode(f)));this.send(a.tree());c=!0;break}c||(null===b.getNodeFromJid(this.jid)?(this._changeConnectStatus(b.Status.CONNFAIL,"x-strophe-bad-non-anon-jid"),this.disconnect("x-strophe-bad-non-anon-jid")):(this._changeConnectStatus(b.Status.AUTHENTICATING,null),this._addSysHandler(this._auth1_cb.bind(this),null,null,null,"_auth_1"),this.send(h({type:"get",to:this.domain,id:"_auth_1"}).c("query",{xmlns:b.NS.AUTH}).c("username",{}).t(b.getNodeFromJid(this.jid)).tree())))},
_sasl_challenge_cb:function(a){a=Base64.decode(b.getText(a));a=this._sasl_mechanism.onChallenge(this,a);var f=g("response",{xmlns:b.NS.SASL});return""!==a&&f.t(Base64.encode(a)),this.send(f.tree()),!0},_auth1_cb:function(){var a=h({type:"set",id:"_auth_2"}).c("query",{xmlns:b.NS.AUTH}).c("username",{}).t(b.getNodeFromJid(this.jid)).up().c("password").t(this.pass);return b.getResourceFromJid(this.jid)||(this.jid=b.getBareJidFromJid(this.jid)+"/strophe"),a.up().c("resource",{}).t(b.getResourceFromJid(this.jid)),
this._addSysHandler(this._auth2_cb.bind(this),null,null,null,"_auth_2"),this.send(a.tree()),!1},_sasl_success_cb:function(a){if(this._sasl_data["server-signature"]){var f;a=Base64.decode(b.getText(a)).match(/([a-z]+)=([^,]+)(,|$)/);if("v"==a[1]&&(f=a[2]),f!=this._sasl_data["server-signature"])return this.deleteHandler(this._sasl_failure_handler),this._sasl_failure_handler=null,this._sasl_challenge_handler&&(this.deleteHandler(this._sasl_challenge_handler),this._sasl_challenge_handler=null),this._sasl_data=
{},this._sasl_failure_cb(null)}return b.info("SASL authentication succeeded."),this._sasl_mechanism&&this._sasl_mechanism.onSuccess(),this.deleteHandler(this._sasl_failure_handler),this._sasl_failure_handler=null,this._sasl_challenge_handler&&(this.deleteHandler(this._sasl_challenge_handler),this._sasl_challenge_handler=null),this._addSysHandler(this._sasl_auth1_cb.bind(this),null,"stream:features",null,null),this._sendRestart(),!1},_sasl_auth1_cb:function(a){this.features=a;var f,c;for(f=0;f<a.childNodes.length;f++)c=
a.childNodes[f],"bind"==c.nodeName&&(this.do_bind=!0),"session"==c.nodeName&&(this.do_session=!0);if(!this.do_bind)return this._changeConnectStatus(b.Status.AUTHFAIL,null),!1;this._addSysHandler(this._sasl_bind_cb.bind(this),null,null,null,"_bind_auth_2");a=b.getResourceFromJid(this.jid);return a?this.send(h({type:"set",id:"_bind_auth_2"}).c("bind",{xmlns:b.NS.BIND}).c("resource",{}).t(a).tree()):this.send(h({type:"set",id:"_bind_auth_2"}).c("bind",{xmlns:b.NS.BIND}).tree()),!1},_sasl_bind_cb:function(a){if("error"==
a.getAttribute("type")){b.info("SASL binding failed.");var f;return 0<a.getElementsByTagName("conflict").length&&(f="conflict"),this._changeConnectStatus(b.Status.AUTHFAIL,f),!1}var c;a=a.getElementsByTagName("bind");return 0<a.length?(c=a[0].getElementsByTagName("jid"),0<c.length&&(this.jid=b.getText(c[0]),this.do_session?(this._addSysHandler(this._sasl_session_cb.bind(this),null,null,null,"_session_auth_2"),this.send(h({type:"set",id:"_session_auth_2"}).c("session",{xmlns:b.NS.SESSION}).tree())):
(this.authenticated=!0,this._changeConnectStatus(b.Status.CONNECTED,null))),void 0):(b.info("SASL binding failed."),this._changeConnectStatus(b.Status.AUTHFAIL,null),!1)},_sasl_session_cb:function(a){if("result"==a.getAttribute("type"))this.authenticated=!0,this._changeConnectStatus(b.Status.CONNECTED,null);else if("error"==a.getAttribute("type"))return b.info("Session creation failed."),this._changeConnectStatus(b.Status.AUTHFAIL,null),!1;return!1},_sasl_failure_cb:function(){return this._sasl_success_handler&&
(this.deleteHandler(this._sasl_success_handler),this._sasl_success_handler=null),this._sasl_challenge_handler&&(this.deleteHandler(this._sasl_challenge_handler),this._sasl_challenge_handler=null),this._sasl_mechanism&&this._sasl_mechanism.onFailure(),this._changeConnectStatus(b.Status.AUTHFAIL,null),!1},_auth2_cb:function(a){return"result"==a.getAttribute("type")?(this.authenticated=!0,this._changeConnectStatus(b.Status.CONNECTED,null)):"error"==a.getAttribute("type")&&(this._changeConnectStatus(b.Status.AUTHFAIL,
null),this.disconnect("authentication failed")),!1},_addSysTimedHandler:function(a,f){var c=new b.TimedHandler(a,f);return c.user=!1,this.addTimeds.push(c),c},_addSysHandler:function(a,f,c,d,e){a=new b.Handler(a,f,c,d,e);return a.user=!1,this.addHandlers.push(a),a},_onDisconnectTimeout:function(){return b.info("_onDisconnectTimeout was called"),this._proto._onDisconnectTimeout(),this._doDisconnect(),!1},_onIdle:function(){for(var a,b,c,d;0<this.addTimeds.length;)this.timedHandlers.push(this.addTimeds.pop());
for(;0<this.removeTimeds.length;)b=this.removeTimeds.pop(),a=this.timedHandlers.indexOf(b),0<=a&&this.timedHandlers.splice(a,1);var e=(new Date).getTime();d=[];for(a=0;a<this.timedHandlers.length;a++)b=this.timedHandlers[a],(this.authenticated||!b.user)&&(c=b.lastCalled+b.period,0>=c-e?b.run()&&d.push(b):d.push(b));this.timedHandlers=d;clearTimeout(this._idleTimeout);this._proto._onIdle();this.connected&&(this._idleTimeout=setTimeout(this._onIdle.bind(this),100))}};d&&d(b,g,e,h,c);b.SASLMechanism=
function(a,b,c){this.name=a;this.isClientFirst=b;this.priority=c};b.SASLMechanism.prototype={test:function(){return!0},onStart:function(a){this._connection=a},onChallenge:function(){throw Error("You should implement challenge handling!");},onFailure:function(){this._connection=null},onSuccess:function(){this._connection=null}};b.SASLAnonymous=function(){};b.SASLAnonymous.prototype=new b.SASLMechanism("ANONYMOUS",!1,10);b.SASLAnonymous.test=function(a){return null===a.authcid};b.Connection.prototype.mechanisms[b.SASLAnonymous.prototype.name]=
b.SASLAnonymous;b.SASLPlain=function(){};b.SASLPlain.prototype=new b.SASLMechanism("PLAIN",!0,20);b.SASLPlain.test=function(a){return null!==a.authcid};b.SASLPlain.prototype.onChallenge=function(a){var b=a.authzid;return b+="\x00",b+=a.authcid,b+="\x00",b+a.pass};b.Connection.prototype.mechanisms[b.SASLPlain.prototype.name]=b.SASLPlain;b.SASLSHA1=function(){};b.SASLSHA1.prototype=new b.SASLMechanism("SCRAM-SHA-1",!0,40);b.SASLSHA1.test=function(a){return null!==a.authcid};b.SASLSHA1.prototype.onChallenge=
function(a,b,c){b=c||MD5.hexdigest(1234567890*Math.random());c="n="+a.authcid;return c+=",r=",c+=b,a._sasl_data.cnonce=b,a._sasl_data["client-first-message-bare"]=c,c="n,,"+c,this.onChallenge=function(a,b){var c,f,d,k,e,g="c=biws,",h=a._sasl_data["client-first-message-bare"]+","+b+",";e=a._sasl_data.cnonce;for(k=/([a-z]+)=([^,]+)(,|$)/;b.match(k);){var u=b.match(k);switch(b=b.replace(u[0],""),u[1]){case "r":c=u[2];break;case "s":f=u[2];break;case "i":d=u[2]}}if(c.substr(0,e.length)!==e)return a._sasl_data=
{},a._sasl_failure_cb();g+="r="+c;h+=g;f=Base64.decode(f);c=f=core_hmac_sha1(a.pass,f+"\x00\x00\x00\u0001");for(e=1;d>e;e++){k=core_hmac_sha1(a.pass,binb2str(f));for(f=0;5>f;f++)c[f]^=k[f];f=k}c=binb2str(c);d=core_hmac_sha1(c,"Client Key");f=str_hmac_sha1(c,"Server Key");c=core_hmac_sha1(str_sha1(binb2str(d)),h);a._sasl_data["server-signature"]=b64_hmac_sha1(f,h);for(f=0;5>f;f++)d[f]^=c[f];return g+(",p="+Base64.encode(binb2str(d)))}.bind(this),c};b.Connection.prototype.mechanisms[b.SASLSHA1.prototype.name]=
b.SASLSHA1;b.SASLMD5=function(){};b.SASLMD5.prototype=new b.SASLMechanism("DIGEST-MD5",!1,30);b.SASLMD5.test=function(a){return null!==a.authcid};b.SASLMD5.prototype._quote=function(a){return'"'+a.replace(/\\/g,"\\\\").replace(/"/g,'\\"')+'"'};b.SASLMD5.prototype.onChallenge=function(a,b,c){var d,e=/([a-z]+)=("[^"]+"|[^,"]+)(?:,|$)/;c=c||MD5.hexdigest(""+1234567890*Math.random());for(var g="",h=null,l="";b.match(e);)switch(d=b.match(e),b=b.replace(d[0],""),d[2]=d[2].replace(/^"(.+)"$/,"$1"),d[1]){case "realm":g=
d[2];break;case "nonce":l=d[2];break;case "host":h=d[2]}b=a.servtype+"/"+a.domain;null!==h&&(b=b+"/"+h);d=MD5.hash(a.authcid+":"+g+":"+this._connection.pass)+":"+l+":"+c;e="AUTHENTICATE:"+b;h="";return h+="charset=utf-8,",h+="username="+this._quote(a.authcid)+",",h+="realm="+this._quote(g)+",",h+="nonce="+this._quote(l)+",",h+="nc=00000001,",h+="cnonce="+this._quote(c)+",",h+="digest-uri="+this._quote(b)+",",h+="response="+MD5.hexdigest(MD5.hexdigest(d)+":"+l+":00000001:"+c+":auth:"+MD5.hexdigest(e))+
",",h+="qop=auth",this.onChallenge=function(){return""}.bind(this),h};b.Connection.prototype.mechanisms[b.SASLMD5.prototype.name]=b.SASLMD5})(function(d,g,e,h,c){window.Strophe=d;window.$build=g;window.$msg=e;window.$iq=h;window.$pres=c});
Strophe.Request=function(d,g,e,h){this.id=++Strophe._requestId;this.xmlData=d;this.data=Strophe.serialize(d);this.func=this.origFunc=g;this.rid=e;this.date=0/0;this.sends=h||0;this.abort=!1;this.dead=null;this.age=function(){return this.date?(new Date-this.date)/1E3:0};this.timeDead=function(){return this.dead?(new Date-this.dead)/1E3:0};this.xhr=this._newXHR()};
Strophe.Request.prototype={getResponse:function(){var d=null;if(this.xhr.responseXML&&this.xhr.responseXML.documentElement){if(d=this.xhr.responseXML.documentElement,"parsererror"==d.tagName)throw Strophe.error("invalid response received"),Strophe.error("responseText: "+this.xhr.responseText),Strophe.error("responseXML: "+Strophe.serialize(this.xhr.responseXML)),"parsererror";}else this.xhr.responseText&&(Strophe.error("invalid response received"),Strophe.error("responseText: "+this.xhr.responseText),
Strophe.error("responseXML: "+Strophe.serialize(this.xhr.responseXML)));return d},_newXHR:function(){var d=null;return window.XMLHttpRequest?(d=new XMLHttpRequest,d.overrideMimeType&&d.overrideMimeType("text/xml")):window.ActiveXObject&&(d=new ActiveXObject("Microsoft.XMLHTTP")),d.onreadystatechange=this.func.bind(null,this),d}};Strophe.Bosh=function(d){this._conn=d;this.rid=Math.floor(4294967295*Math.random());this.sid=null;this.hold=1;this.wait=60;this.window=5;this._requests=[]};
Strophe.Bosh.prototype={strip:null,_buildBody:function(){var d=$build("body",{rid:this.rid++,xmlns:Strophe.NS.HTTPBIND});return null!==this.sid&&d.attrs({sid:this.sid}),d},_reset:function(){this.rid=Math.floor(4294967295*Math.random());this.sid=null},_connect:function(d,g,e){this.wait=d||this.wait;this.hold=g||this.hold;d=this._buildBody().attrs({to:this._conn.domain,"xml:lang":"en",wait:this.wait,hold:this.hold,content:"text/xml; charset=utf-8",ver:"1.6","xmpp:version":"1.0","xmlns:xmpp":Strophe.NS.BOSH});
e&&d.attrs({route:e});e=this._conn._connect_cb;this._requests.push(new Strophe.Request(d.tree(),this._onRequestStateChange.bind(this,e.bind(this._conn)),d.tree().getAttribute("rid")));this._throttledRequestHandler()},_attach:function(d,g,e,h,c,b,a){this._conn.jid=d;this.sid=g;this.rid=e;this._conn.connect_callback=h;this._conn.domain=Strophe.getDomainFromJid(this._conn.jid);this._conn.authenticated=!0;this._conn.connected=!0;this.wait=c||this.wait;this.hold=b||this.hold;this.window=a||this.window;
this._conn._changeConnectStatus(Strophe.Status.ATTACHED,null)},_connect_cb:function(d){var g,e,h=d.getAttribute("type");if(null!==h&&"terminate"==h)return Strophe.error("BOSH-Connection failed: "+g),g=d.getAttribute("condition"),e=d.getElementsByTagName("conflict"),null!==g?("remote-stream-error"==g&&0<e.length&&(g="conflict"),this._conn._changeConnectStatus(Strophe.Status.CONNFAIL,g)):this._conn._changeConnectStatus(Strophe.Status.CONNFAIL,"unknown"),this._conn._doDisconnect(),Strophe.Status.CONNFAIL;
this.sid||(this.sid=d.getAttribute("sid"));(g=d.getAttribute("requests"))&&(this.window=parseInt(g,10));(g=d.getAttribute("hold"))&&(this.hold=parseInt(g,10));(d=d.getAttribute("wait"))&&(this.wait=parseInt(d,10))},_disconnect:function(d){this._sendTerminate(d)},_doDisconnect:function(){this.sid=null;this.rid=Math.floor(4294967295*Math.random())},_emptyQueue:function(){return 0===this._requests.length},_hitError:function(d){this.errors++;Strophe.warn("request errored, status: "+d+", number of errors: "+
this.errors);4<this.errors&&this._onDisconnectTimeout()},_no_auth_received:function(d){d=d?d.bind(this._conn):this._conn._connect_cb.bind(this._conn);var g=this._buildBody();this._requests.push(new Strophe.Request(g.tree(),this._onRequestStateChange.bind(this,d.bind(this._conn)),g.tree().getAttribute("rid")));this._throttledRequestHandler()},_onDisconnectTimeout:function(){for(var d;0<this._requests.length;)d=this._requests.pop(),d.abort=!0,d.xhr.abort(),d.xhr.onreadystatechange=function(){}},_onIdle:function(){var d=
this._conn._data;if(this._conn.authenticated&&0===this._requests.length&&0===d.length&&!this._conn.disconnecting&&(Strophe.info("no requests during idle cycle, sending blank request"),d.push(null)),2>this._requests.length&&0<d.length&&!this._conn.paused){for(var g=this._buildBody(),e=0;e<d.length;e++)null!==d[e]&&("restart"===d[e]?g.attrs({to:this._conn.domain,"xml:lang":"en","xmpp:restart":"true","xmlns:xmpp":Strophe.NS.BOSH}):g.cnode(d[e]).up());delete this._conn._data;this._conn._data=[];this._requests.push(new Strophe.Request(g.tree(),
this._onRequestStateChange.bind(this,this._conn._dataRecv.bind(this._conn)),g.tree().getAttribute("rid")));this._processRequest(this._requests.length-1)}0<this._requests.length&&(d=this._requests[0].age(),null!==this._requests[0].dead&&this._requests[0].timeDead()>Math.floor(Strophe.SECONDARY_TIMEOUT*this.wait)&&this._throttledRequestHandler(),d>Math.floor(Strophe.TIMEOUT*this.wait)&&(Strophe.warn("Request "+this._requests[0].id+" timed out, over "+Math.floor(Strophe.TIMEOUT*this.wait)+" seconds since last activity"),
this._throttledRequestHandler()))},_onRequestStateChange:function(d,g){if(Strophe.debug("request id "+g.id+"."+g.sends+" state changed to "+g.xhr.readyState),g.abort)return g.abort=!1,void 0;var e;if(4==g.xhr.readyState){e=0;try{e=g.xhr.status}catch(h){}if("undefined"==typeof e&&(e=0),this.disconnecting&&400<=e)return this._hitError(e),void 0;var c=this._requests[0]==g,b=this._requests[1]==g;(0<e&&500>e||5<g.sends)&&(this._removeRequest(g),Strophe.debug("request id "+g.id+" should now be removed"));
200==e?((b||c&&0<this._requests.length&&this._requests[0].age()>Math.floor(Strophe.SECONDARY_TIMEOUT*this.wait))&&this._restartRequest(0),Strophe.debug("request id "+g.id+"."+g.sends+" got 200"),d(g),this.errors=0):(Strophe.error("request id "+g.id+"."+g.sends+" error "+e+" happened"),(0===e||400<=e&&600>e||12E3<=e)&&(this._hitError(e),400<=e&&500>e&&(this._conn._changeConnectStatus(Strophe.Status.DISCONNECTING,null),this._conn._doDisconnect())));0<e&&500>e||5<g.sends||this._throttledRequestHandler()}},
_processRequest:function(d){var g=this,e=this._requests[d],h=-1;try{4==e.xhr.readyState&&(h=e.xhr.status)}catch(c){Strophe.error("caught an error in _requests["+d+"], reqStatus: "+h)}if("undefined"==typeof h&&(h=-1),e.sends>this.maxRetries)return this._onDisconnectTimeout(),void 0;var b=e.age(),b=!isNaN(b)&&b>Math.floor(Strophe.TIMEOUT*this.wait),a=null!==e.dead&&e.timeDead()>Math.floor(Strophe.SECONDARY_TIMEOUT*this.wait),h=4==e.xhr.readyState&&(1>h||500<=h);if((b||a||h)&&(a&&Strophe.error("Request "+
this._requests[d].id+" timed out (secondary), restarting"),e.abort=!0,e.xhr.abort(),e.xhr.onreadystatechange=function(){},this._requests[d]=new Strophe.Request(e.xmlData,e.origFunc,e.rid,e.sends),e=this._requests[d]),0===e.xhr.readyState){Strophe.debug("request id "+e.id+"."+e.sends+" posting");try{e.xhr.open("POST",this._conn.service,this._conn.options.sync?!1:!0)}catch(f){return Strophe.error("XHR open failed."),this._conn.connected||this._conn._changeConnectStatus(Strophe.Status.CONNFAIL,"bad-service"),
this._conn.disconnect(),void 0}d=function(){if(e.date=new Date,g._conn.options.customHeaders){var a=g._conn.options.customHeaders,b;for(b in a)a.hasOwnProperty(b)&&e.xhr.setRequestHeader(b,a[b])}e.xhr.send(e.data)};1<e.sends?(h=1E3*Math.min(Math.floor(Strophe.TIMEOUT*this.wait),Math.pow(e.sends,3)),setTimeout(d,h)):d();e.sends++;this._conn.xmlOutput!==Strophe.Connection.prototype.xmlOutput&&(e.xmlData.nodeName===this.strip&&e.xmlData.childNodes.length?this._conn.xmlOutput(e.xmlData.childNodes[0]):
this._conn.xmlOutput(e.xmlData));this._conn.rawOutput!==Strophe.Connection.prototype.rawOutput&&this._conn.rawOutput(e.data)}else Strophe.debug("_processRequest: "+(0===d?"first":"second")+" request has readyState of "+e.xhr.readyState)},_removeRequest:function(d){Strophe.debug("removing request");var g;for(g=this._requests.length-1;0<=g;g--)d==this._requests[g]&&this._requests.splice(g,1);d.xhr.onreadystatechange=function(){};this._throttledRequestHandler()},_restartRequest:function(d){var g=this._requests[d];
null===g.dead&&(g.dead=new Date);this._processRequest(d)},_reqToData:function(d){try{return d.getResponse()}catch(g){if("parsererror"!=g)throw g;this._conn.disconnect("strophe-parsererror")}},_sendTerminate:function(d){Strophe.info("_sendTerminate was called");var g=this._buildBody().attrs({type:"terminate"});d&&g.cnode(d.tree());d=new Strophe.Request(g.tree(),this._onRequestStateChange.bind(this,this._conn._dataRecv.bind(this._conn)),g.tree().getAttribute("rid"));this._requests.push(d);this._throttledRequestHandler()},
_send:function(){clearTimeout(this._conn._idleTimeout);this._throttledRequestHandler();this._conn._idleTimeout=setTimeout(this._conn._onIdle.bind(this._conn),100)},_sendRestart:function(){this._throttledRequestHandler();clearTimeout(this._conn._idleTimeout)},_throttledRequestHandler:function(){this._requests?Strophe.debug("_throttledRequestHandler called with "+this._requests.length+" requests"):Strophe.debug("_throttledRequestHandler called with undefined requests");this._requests&&0!==this._requests.length&&
(0<this._requests.length&&this._processRequest(0),1<this._requests.length&&Math.abs(this._requests[0].rid-this._requests[1].rid)<this.window&&this._processRequest(1))}};Strophe.Websocket=function(d){this._conn=d;this.strip="stream:stream";var g=d.service;if(0!==g.indexOf("ws:")&&0!==g.indexOf("wss:")){var e;e=""+("ws"===d.options.protocol&&"https:"!==window.location.protocol?"ws":"wss");e+="://"+window.location.host;e+=0!==g.indexOf("/")?window.location.pathname+g:g;d.service=e}};
Strophe.Websocket.prototype={_buildStream:function(){return $build("stream:stream",{to:this._conn.domain,xmlns:Strophe.NS.CLIENT,"xmlns:stream":Strophe.NS.STREAM,version:"1.0"})},_check_streamerror:function(d,g){var e=d.getElementsByTagName("stream:error");if(0===e.length)return!1;for(var h=e[0],c=e="",b=0;b<h.childNodes.length;b++){var a=h.childNodes[b];if("urn:ietf:params:xml:ns:xmpp-streams"!==a.getAttribute("xmlns"))break;"text"===a.nodeName?c=a.textContent:e=a.nodeName}h="WebSocket stream error: ";
return h+=e?e:"unknown",c&&(h+=" - "+e),Strophe.error(h),this._conn._changeConnectStatus(g,e),this._conn._doDisconnect(),!0},_reset:function(){},_connect:function(){this._closeSocket();this.socket=new WebSocket(this._conn.service,"xmpp");this.socket.onopen=this._onOpen.bind(this);this.socket.onerror=this._onError.bind(this);this.socket.onclose=this._onClose.bind(this);this.socket.onmessage=this._connect_cb_wrapper.bind(this)},_connect_cb:function(d){return this._check_streamerror(d,Strophe.Status.CONNFAIL)?
Strophe.Status.CONNFAIL:void 0},_handleStreamStart:function(d){var g=!1,e=d.getAttribute("xmlns");"string"!=typeof e?g="Missing xmlns in stream:stream":e!==Strophe.NS.CLIENT&&(g="Wrong xmlns in stream:stream: "+e);e=d.namespaceURI;"string"!=typeof e?g="Missing xmlns:stream in stream:stream":e!==Strophe.NS.STREAM&&(g="Wrong xmlns:stream in stream:stream: "+e);d=d.getAttribute("version");return"string"!=typeof d?g="Missing version in stream:stream":"1.0"!==d&&(g="Wrong version in stream:stream: "+d),
g?(this._conn._changeConnectStatus(Strophe.Status.CONNFAIL,g),this._conn._doDisconnect(),!1):!0},_connect_cb_wrapper:function(d){if(0===d.data.indexOf("<stream:stream ")||0===d.data.indexOf("<?xml")){var g=d.data.replace(/^(<\?.*?\?>\s*)*/,"");""!==g&&(g=d.data.replace(/<stream:stream (.*[^\/])>/,"<stream:stream $1/>"),g=(new DOMParser).parseFromString(g,"text/xml").documentElement,this._conn.xmlInput(g),this._conn.rawInput(d.data),this._handleStreamStart(g)&&(this._connect_cb(g),this.streamStart=
d.data.replace(/^<stream:(.*)\/>$/,"<stream:$1>")))}else{if("</stream:stream>"===d.data)return this._conn.rawInput(d.data),this._conn.xmlInput(document.createElement("stream:stream")),this._conn._changeConnectStatus(Strophe.Status.CONNFAIL,"Received closing stream"),this._conn._doDisconnect(),void 0;g=this._streamWrap(d.data);g=(new DOMParser).parseFromString(g,"text/xml").documentElement;this.socket.onmessage=this._onMessage.bind(this);this._conn._connect_cb(g,null,d.data)}},_disconnect:function(d){if(this.socket.readyState!==
WebSocket.CLOSED){d&&this._conn.send(d);this._conn.xmlOutput(document.createElement("stream:stream"));this._conn.rawOutput("</stream:stream>");try{this.socket.send("</stream:stream>")}catch(g){Strophe.info("Couldn't send closing stream tag.")}}this._conn._doDisconnect()},_doDisconnect:function(){Strophe.info("WebSockets _doDisconnect was called");this._closeSocket()},_streamWrap:function(d){return this.streamStart+d+"</stream:stream>"},_closeSocket:function(){if(this.socket)try{this.socket.close()}catch(d){}this.socket=
null},_emptyQueue:function(){return!0},_onClose:function(){this._conn.connected&&!this._conn.disconnecting?(Strophe.error("Websocket closed unexcectedly"),this._conn._doDisconnect()):Strophe.info("Websocket closed")},_no_auth_received:function(d){Strophe.error("Server did not send any auth methods");this._conn._changeConnectStatus(Strophe.Status.CONNFAIL,"Server did not send any auth methods");d&&d.bind(this._conn)();this._conn._doDisconnect()},_onDisconnectTimeout:function(){},_onError:function(d){Strophe.error("Websocket error "+
d);this._conn._changeConnectStatus(Strophe.Status.CONNFAIL,"The WebSocket connection could not be established was disconnected.");this._disconnect()},_onIdle:function(){var d=this._conn._data;if(0<d.length&&!this._conn.paused){for(var g=0;g<d.length;g++)if(null!==d[g]){var e,h;"restart"===d[g]?(e=this._buildStream(),h=this._removeClosingTag(e),e=e.tree()):(e=d[g],h=Strophe.serialize(e));this._conn.xmlOutput(e);this._conn.rawOutput(h);this.socket.send(h)}this._conn._data=[]}},_onMessage:function(d){var g,
e;if("</stream:stream>"===d.data)return this._conn.rawInput("</stream:stream>"),this._conn.xmlInput(document.createElement("stream:stream")),this._conn.disconnecting||this._conn._doDisconnect(),void 0;if(0===d.data.search("<stream:stream ")){if(e=d.data.replace(/<stream:stream (.*[^\/])>/,"<stream:stream $1/>"),g=(new DOMParser).parseFromString(e,"text/xml").documentElement,!this._handleStreamStart(g))return}else e=this._streamWrap(d.data),g=(new DOMParser).parseFromString(e,"text/xml").documentElement;
if(!this._check_streamerror(g,Strophe.Status.ERROR))return this._conn.disconnecting&&"presence"===g.firstChild.nodeName&&"unavailable"===g.firstChild.getAttribute("type")?(this._conn.xmlInput(g),this._conn.rawInput(Strophe.serialize(g)),void 0):(this._conn._dataRecv(g,d.data),void 0)},_onOpen:function(){Strophe.info("Websocket open");var d=this._buildStream();this._conn.xmlOutput(d.tree());d=this._removeClosingTag(d);this._conn.rawOutput(d);this.socket.send(d)},_removeClosingTag:function(d){return Strophe.serialize(d).replace(/<(stream:stream .*[^\/])\/>$/,
"<$1>")},_reqToData:function(d){return d},_send:function(){this._conn.flush()},_sendRestart:function(){clearTimeout(this._conn._idleTimeout);this._conn._onIdle.bind(this._conn)()}};
(function(){var d,g,e={}.hasOwnProperty,h=function(c,b){return function(){return c.apply(b,arguments)}};Strophe.addConnectionPlugin("muc",{_connection:null,rooms:{},roomNames:[],init:function(c){this._connection=c;this._muc_handler=null;Strophe.addNamespace("MUC_OWNER",Strophe.NS.MUC+"#owner");Strophe.addNamespace("MUC_ADMIN",Strophe.NS.MUC+"#admin");Strophe.addNamespace("MUC_USER",Strophe.NS.MUC+"#user");Strophe.addNamespace("MUC_ROOMCONF",Strophe.NS.MUC+"#roomconfig");return Strophe.addNamespace("MUC_REGISTER",
"jabber:iq:register")},join:function(c,b,a,f,d,e,h){var r;r=this.test_append_nick(c,b);r=$pres({from:this._connection.jid,to:r}).c("x",{xmlns:Strophe.NS.MUC});null!=h&&(r=r.c("history",h).up());null!=e&&r.cnode(Strophe.xmlElement("password",[],e));"undefined"!==typeof extended_presence&&null!==extended_presence&&r.up.cnode(extended_presence);null==this._muc_handler&&(this._muc_handler=this._connection.addHandler(function(a){return function(b){var f,d,e,g,k,h;f=b.getAttribute("from");if(!f)return!0;
f=f.split("/")[0];if(!a.rooms[f])return!0;c=a.rooms[f];f={};if("message"===b.nodeName)f=c._message_handlers;else if("presence"===b.nodeName&&(d=b.getElementsByTagName("x"),0<d.length))for(k=0,h=d.length;k<h;k++)if(g=d[k],(g=g.getAttribute("xmlns"))&&g.match(Strophe.NS.MUC)){f=c._presence_handlers;break}for(e in f)d=f[e],d(b,c)||delete f[e];return!0}}(this)));this.rooms.hasOwnProperty(c)||(this.rooms[c]=new g(this,c,b,e),this.roomNames.push(c));f&&this.rooms[c].addHandler("presence",f);a&&this.rooms[c].addHandler("message",
a);d&&this.rooms[c].addHandler("roster",d);return this._connection.send(r)},leave:function(c,b,a,f){var d;d=this.roomNames.indexOf(c);delete this.rooms[c];0<=d&&(this.roomNames.splice(d,1),0===this.roomNames.length&&(this._connection.deleteHandler(this._muc_handler),this._muc_handler=null));b=this.test_append_nick(c,b);c=this._connection.getUniqueId();b=$pres({type:"unavailable",id:c,from:this._connection.jid,to:b});null!=f&&b.c("status",f);null!=a&&this._connection.addHandler(a,null,"presence",null,
c);this._connection.send(b);return c},message:function(c,b,a,f,d,e){c=this.test_append_nick(c,b);d=d||(null!=b?"chat":"groupchat");e=e||this._connection.getUniqueId();b=$msg({to:c,from:this._connection.jid,type:d,id:e}).c("body",{xmlns:Strophe.NS.CLIENT}).t(a);b.up();null!=f&&(b.c("html",{xmlns:Strophe.NS.XHTML_IM}).c("body",{xmlns:Strophe.NS.XHTML}).h(f),0===b.node.childNodes.length?(f=b.node.parentNode,b.up().up(),b.node.removeChild(f)):b.up().up());b.c("x",{xmlns:"jabber:x:event"}).c("composing");
this._connection.send(b);return e},groupchat:function(c,b,a,f){return this.message(c,null,b,a,void 0,f)},invite:function(c,b,a){var f;f=this._connection.getUniqueId();c=$msg({from:this._connection.jid,to:c,id:f}).c("x",{xmlns:Strophe.NS.MUC_USER}).c("invite",{to:b});null!=a&&c.c("reason",a);this._connection.send(c);return f},multipleInvites:function(c,b,a){var f,d,e,g;f=this._connection.getUniqueId();c=$msg({from:this._connection.jid,to:c,id:f}).c("x",{xmlns:Strophe.NS.MUC_USER});e=0;for(g=b.length;e<
g;e++)d=b[e],c.c("invite",{to:d}),null!=a&&(c.c("reason",a),c.up()),c.up();this._connection.send(c);return f},directInvite:function(c,b,a,f){var d;d=this._connection.getUniqueId();c={xmlns:"jabber:x:conference",jid:c};null!=a&&(c.reason=a);null!=f&&(c.password=f);b=$msg({from:this._connection.jid,to:b,id:d}).c("x",c);this._connection.send(b);return d},queryOccupants:function(c,b,a){var f;f={xmlns:Strophe.NS.DISCO_ITEMS};c=$iq({from:this._connection.jid,to:c,type:"get"}).c("query",f);return this._connection.sendIQ(c,
b,a)},configure:function(c,b,a){c=$iq({to:c,type:"get"}).c("query",{xmlns:Strophe.NS.MUC_OWNER}).tree();return this._connection.sendIQ(c,b,a)},cancelConfigure:function(c){c=$iq({to:c,type:"set"}).c("query",{xmlns:Strophe.NS.MUC_OWNER}).c("x",{xmlns:"jabber:x:data",type:"cancel"}).tree();return this._connection.sendIQ(c)},saveConfiguration:function(c,b,a,f){var d,e,g;d=$iq({to:c,type:"set"}).c("query",{xmlns:Strophe.NS.MUC_OWNER});if("undefined"!==typeof Form&&b instanceof Form)b.type="submit",d.cnode(b.toXML());
else for(d.c("x",{xmlns:"jabber:x:data",type:"submit"}),e=0,g=b.length;e<g;e++)c=b[e],d.cnode(c).up();b=d.tree();return this._connection.sendIQ(b,a,f)},createInstantRoom:function(c,b,a){c=$iq({to:c,type:"set"}).c("query",{xmlns:Strophe.NS.MUC_OWNER}).c("x",{xmlns:"jabber:x:data",type:"submit"});return this._connection.sendIQ(c.tree(),b,a)},createConfiguredRoom:function(c,b,a,f){var d,g;c=$iq({to:c,type:"set"}).c("query",{xmlns:Strophe.NS.MUC_OWNER}).c("x",{xmlns:"jabber:x:data",type:"submit"});c.c("field",
{"var":"FORM_TYPE"}).c("value").t("http://jabber.org/protocol/muc#roomconfig").up().up();for(d in b)e.call(b,d)&&(g=b[d],c.c("field",{"var":d}).c("value").t(g).up().up());return this._connection.sendIQ(c.tree(),a,f)},setTopic:function(c,b){var a;a=$msg({to:c,from:this._connection.jid,type:"groupchat"}).c("subject",{xmlns:"jabber:client"}).t(b);return this._connection.send(a.tree())},_modifyPrivilege:function(c,b,a,f,d){c=$iq({to:c,type:"set"}).c("query",{xmlns:Strophe.NS.MUC_ADMIN}).cnode(b.node);
null!=a&&c.c("reason",a);return this._connection.sendIQ(c.tree(),f,d)},modifyRole:function(c,b,a,f,d,e){b=$build("item",{nick:b,role:a});return this._modifyPrivilege(c,b,f,d,e)},kick:function(c,b,a,f,d){return this.modifyRole(c,b,"none",a,f,d)},voice:function(c,b,a,f,d){return this.modifyRole(c,b,"participant",a,f,d)},mute:function(c,b,a,f,d){return this.modifyRole(c,b,"visitor",a,f,d)},op:function(c,b,a,f,d){return this.modifyRole(c,b,"moderator",a,f,d)},deop:function(c,b,a,f,d){return this.modifyRole(c,
b,"participant",a,f,d)},modifyAffiliation:function(c,b,a,f,d,e){b=$build("item",{jid:b,affiliation:a});return this._modifyPrivilege(c,b,f,d,e)},ban:function(c,b,a,f,d){return this.modifyAffiliation(c,b,"outcast",a,f,d)},member:function(c,b,a,f,d){return this.modifyAffiliation(c,b,"member",a,f,d)},revoke:function(c,b,a,f,d){return this.modifyAffiliation(c,b,"none",a,f,d)},owner:function(c,b,a,f,d){return this.modifyAffiliation(c,b,"owner",a,f,d)},admin:function(c,b,a,d,e){return this.modifyAffiliation(c,
b,"admin",a,d,e)},changeNick:function(c,b){var a;a=this.test_append_nick(c,b);a=$pres({from:this._connection.jid,to:a,id:this._connection.getUniqueId()});return this._connection.send(a.tree())},setStatus:function(c,b,a,d){c=this.test_append_nick(c,b);c=$pres({from:this._connection.jid,to:c});null!=a&&c.c("show",a).up();null!=d&&c.c("status",d);return this._connection.send(c.tree())},registrationRequest:function(c,b,a){c=$iq({to:c,from:this._connection.jid,type:"get"}).c("query",{xmlns:Strophe.NS.MUC_REGISTER});
return this._connection.sendIQ(c,function(a){var c,d,e,g,h;c=a.getElementsByTagName("field");e={required:[],optional:[]};g=0;for(h=c.length;g<h;g++)a=c[g],d={"var":a.getAttribute("var"),label:a.getAttribute("label"),type:a.getAttribute("type")},0<a.getElementsByTagName("required").length?e.required.push(d):e.optional.push(d);return b(e)},a)},submitRegistrationForm:function(c,b,a,d){var e,g;c=$iq({to:c,type:"set"}).c("query",{xmlns:Strophe.NS.MUC_REGISTER});c.c("x",{xmlns:"jabber:x:data",type:"submit"});
c.c("field",{"var":"FORM_TYPE"}).c("value").t("http://jabber.org/protocol/muc#register").up().up();for(e in b)g=b[e],c.c("field",{"var":e}).c("value").t(g).up().up();return this._connection.sendIQ(c,a,d)},listRooms:function(c,b,a){c=$iq({to:c,from:this._connection.jid,type:"get"}).c("query",{xmlns:Strophe.NS.DISCO_ITEMS});return this._connection.sendIQ(c,b,a)},test_append_nick:function(c,b){var a,d;d=Strophe.escapeNode(Strophe.getNodeFromJid(c));a=Strophe.getDomainFromJid(c);return d+"@"+a+(null!=
b?"/"+b:"")}});g=function(){function c(b,a,c,d){this.client=b;this.name=a;this.nick=c;this.password=d;this._roomRosterHandler=h(this._roomRosterHandler,this);this._addOccupant=h(this._addOccupant,this);this.roster={};this._message_handlers={};this._presence_handlers={};this._roster_handlers={};this._handler_ids=0;b.muc&&(this.client=b.muc);this.name=Strophe.getBareJidFromJid(a);this.addHandler("presence",this._roomRosterHandler)}c.prototype.join=function(b,a,c){return this.client.join(this.name,this.nick,
b,a,c,this.password)};c.prototype.leave=function(b,a){this.client.leave(this.name,this.nick,b,a);return delete this.client.rooms[this.name]};c.prototype.message=function(b,a,c,d){return this.client.message(this.name,b,a,c,d)};c.prototype.groupchat=function(b,a){return this.client.groupchat(this.name,b,a)};c.prototype.invite=function(b,a){return this.client.invite(this.name,b,a)};c.prototype.multipleInvites=function(b,a){return this.client.invite(this.name,b,a)};c.prototype.directInvite=function(b,
a){return this.client.directInvite(this.name,b,a,this.password)};c.prototype.configure=function(b){return this.client.configure(this.name,b)};c.prototype.cancelConfigure=function(){return this.client.cancelConfigure(this.name)};c.prototype.saveConfiguration=function(b){return this.client.saveConfiguration(this.name,b)};c.prototype.queryOccupants=function(b,a){return this.client.queryOccupants(this.name,b,a)};c.prototype.setTopic=function(b){return this.client.setTopic(this.name,b)};c.prototype.modifyRole=
function(b,a,c,d,e){return this.client.modifyRole(this.name,b,a,c,d,e)};c.prototype.kick=function(b,a,c,d){return this.client.kick(this.name,b,a,c,d)};c.prototype.voice=function(b,a,c,d){return this.client.voice(this.name,b,a,c,d)};c.prototype.mute=function(b,a,c,d){return this.client.mute(this.name,b,a,c,d)};c.prototype.op=function(b,a,c,d){return this.client.op(this.name,b,a,c,d)};c.prototype.deop=function(b,a,c,d){return this.client.deop(this.name,b,a,c,d)};c.prototype.modifyAffiliation=function(b,
a,c,d,e){return this.client.modifyAffiliation(this.name,b,a,c,d,e)};c.prototype.ban=function(b,a,c,d){return this.client.ban(this.name,b,a,c,d)};c.prototype.member=function(b,a,c,d){return this.client.member(this.name,b,a,c,d)};c.prototype.revoke=function(b,a,c,d){return this.client.revoke(this.name,b,a,c,d)};c.prototype.owner=function(b,a,c,d){return this.client.owner(this.name,b,a,c,d)};c.prototype.admin=function(b,a,c,d){return this.client.admin(this.name,b,a,c,d)};c.prototype.changeNick=function(b){this.nick=
b;return this.client.changeNick(this.name,b)};c.prototype.setStatus=function(b,a){return this.client.setStatus(this.name,this.nick,b,a)};c.prototype.addHandler=function(b,a){var c;c=this._handler_ids++;switch(b){case "presence":this._presence_handlers[c]=a;break;case "message":this._message_handlers[c]=a;break;case "roster":this._roster_handlers[c]=a;break;default:return this._handler_ids--,null}return c};c.prototype.removeHandler=function(b){delete this._presence_handlers[b];delete this._message_handlers[b];
return delete this._roster_handlers[b]};c.prototype._addOccupant=function(b){b=new d(b,this);return this.roster[b.nick]=b};c.prototype._roomRosterHandler=function(b){var a,d,e;b=c._parsePresence(b);e=b.nick;d=b.newnick||null;switch(b.type){case "error":return!0;case "unavailable":d&&(b.nick=d,this.roster[e]&&this.roster[d]&&(this.roster[e].update(this.roster[d]),this.roster[d]=this.roster[e]),this.roster[e]&&!this.roster[d]&&(this.roster[d]=this.roster[e].update(b)));delete this.roster[e];break;default:this.roster[e]?
this.roster[e].update(b):this._addOccupant(b)}d=this._roster_handlers;for(a in d)b=d[a],b(this.roster,this)||delete this._roster_handlers[a];return!0};c._parsePresence=function(b){var a,c,d,e,g,h,s;c={};c.nick=Strophe.getResourceFromJid(b.getAttribute("from"));c.type=b.getAttribute("type");c.states=[];h=b.childNodes;b=0;for(e=h.length;b<e;b++)switch(a=h[b],a.nodeName){case "status":c.status=a.textContent||null;break;case "show":c.show=a.textContent||null;break;case "x":if(a.getAttribute("xmlns")===
Strophe.NS.MUC_USER)for(s=a.childNodes,d=0,g=s.length;d<g;d++)switch(a=s[d],a.nodeName){case "item":c.affiliation=a.getAttribute("affiliation");c.role=a.getAttribute("role");c.jid=a.getAttribute("jid");c.newnick=a.getAttribute("nick");break;case "status":a.getAttribute("code")&&c.states.push(a.getAttribute("code"))}}return c};return c}();(function(){function c(b){this.parse=h(this.parse,this);null!=b&&this.parse(b)}c.prototype.parse=function(b){var a,c,d,e,g,h,s;b=b.getElementsByTagName("query")[0].childNodes;
this.identities=[];this.features=[];this.x=[];e=0;for(h=b.length;e<h;e++)switch(a=b[e],c=a.attributes,a.nodeName){case "identity":d={};g=0;for(s=c.length;g<s;g++)a=c[g],d[a.name]=a.textContent;this.identities.push(d);break;case "feature":this.features.push(a.getAttribute("var"));break;case "x":if("FORM_TYPE"===!a.childNodes[0].getAttribute("var")||"hidden"===!a.childNodes[0].getAttribute("type"))break;g=a.childNodes;a=0;for(d=g.length;a<d;a++)c=g[a],c.attributes.type||this.x.push({"var":c.getAttribute("var"),
label:c.getAttribute("label")||"",value:c.firstChild.textContent||""})}return{identities:this.identities,features:this.features,x:this.x}};return c})();d=function(){function c(b,a){this.room=a;this.update=h(this.update,this);this.admin=h(this.admin,this);this.owner=h(this.owner,this);this.revoke=h(this.revoke,this);this.member=h(this.member,this);this.ban=h(this.ban,this);this.modifyAffiliation=h(this.modifyAffiliation,this);this.deop=h(this.deop,this);this.op=h(this.op,this);this.mute=h(this.mute,
this);this.voice=h(this.voice,this);this.kick=h(this.kick,this);this.modifyRole=h(this.modifyRole,this);this.update(b)}c.prototype.modifyRole=function(b,a,c,d){return this.room.modifyRole(this.nick,b,a,c,d)};c.prototype.kick=function(b,a,c){return this.room.kick(this.nick,b,a,c)};c.prototype.voice=function(b,a,c){return this.room.voice(this.nick,b,a,c)};c.prototype.mute=function(b,a,c){return this.room.mute(this.nick,b,a,c)};c.prototype.op=function(b,a,c){return this.room.op(this.nick,b,a,c)};c.prototype.deop=
function(b,a,c){return this.room.deop(this.nick,b,a,c)};c.prototype.modifyAffiliation=function(b,a,c,d){return this.room.modifyAffiliation(this.jid,b,a,c,d)};c.prototype.ban=function(b,a,c){return this.room.ban(this.jid,b,a,c)};c.prototype.member=function(b,a,c){return this.room.member(this.jid,b,a,c)};c.prototype.revoke=function(b,a,c){return this.room.revoke(this.jid,b,a,c)};c.prototype.owner=function(b,a,c){return this.room.owner(this.jid,b,a,c)};c.prototype.admin=function(b,a,c){return this.room.admin(this.jid,
b,a,c)};c.prototype.update=function(b){this.nick=b.nick||null;this.affiliation=b.affiliation||null;this.role=b.role||null;this.jid=b.jid||null;this.status=b.status||null;this.show=b.show||null;return this};return c}()}).call(this);